FROM node:10-alpine as builder

WORKDIR /react-app
COPY package.json package-lock.json ./
RUN npm install --production
COPY . .
RUN npm run build


FROM nginx:alpine

COPY ./.nginx/nginx-react.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /react-app/build /usr/share/nginx/html

EXPOSE 3000 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
