# This is a lightweight Dockerfile for building ARM-based apps
# It supports Node 16, AWS CLI v2 and a necessary tools (jq, perl, bash, open ssh, git)
# You can custom it to fit your need
FROM node:16-alpine

USER root


# install glibc compatibility for alpine
RUN apk update && apk --no-cache add \
        make g++ \
        openssh-client \
        bash \
        gawk \
        perl \
        jq \
        binutils \
        curl \
        git \
        unzip \
        binutils
RUN apk add aws-cli --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
RUN rm -rf /var/cache/apk/*
